/**
 * Copyright (C) 2024  Jochem-W
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
// Code generated by pggen. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v5"
)

// Querier is a typesafe Go interface backed by SQL queries.
type Querier interface {
	GetSubscriptions(ctx context.Context, did string) ([]GetSubscriptionsRow, error)

	ClearToken(ctx context.Context, id string) (pgconn.CommandTag, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn  genericConn   // underlying Postgres transport to use
	types *typeResolver // resolve types by name
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// NewQuerier creates a DBQuerier that implements Querier.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn, types: newTypeResolver()}
}

// typeResolver looks up the pgtype.ValueTranscoder by Postgres type name.
type typeResolver struct {
	connInfo *pgtype.ConnInfo // types by Postgres type name
}

func newTypeResolver() *typeResolver {
	ci := pgtype.NewConnInfo()
	return &typeResolver{connInfo: ci}
}

// findValue find the OID, and pgtype.ValueTranscoder for a Postgres type name.
func (tr *typeResolver) findValue(name string) (uint32, pgtype.ValueTranscoder, bool) {
	typ, ok := tr.connInfo.DataTypeForName(name)
	if !ok {
		return 0, nil, false
	}
	v := pgtype.NewValue(typ.Value)
	return typ.OID, v.(pgtype.ValueTranscoder), true
}

// setValue sets the value of a ValueTranscoder to a value that should always
// work and panics if it fails.
func (tr *typeResolver) setValue(vt pgtype.ValueTranscoder, val interface{}) pgtype.ValueTranscoder {
	if err := vt.Set(val); err != nil {
		panic(fmt.Sprintf("set ValueTranscoder %T to %+v: %s", vt, val, err))
	}
	return vt
}

const getSubscriptionsSQL = `SELECT account.token, subscription.posts, subscription.reposts, subscription.replies FROM subscription INNER JOIN account ON subscription.account = account.id WHERE account.token IS NOT NULL AND subscription.target = $1;`

type GetSubscriptionsRow struct {
	Token   *string `json:"token"`
	Posts   *bool   `json:"posts"`
	Reposts *bool   `json:"reposts"`
	Replies *bool   `json:"replies"`
}

// GetSubscriptions implements Querier.GetSubscriptions.
func (q *DBQuerier) GetSubscriptions(ctx context.Context, did string) ([]GetSubscriptionsRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "GetSubscriptions")
	rows, err := q.conn.Query(ctx, getSubscriptionsSQL, did)
	if err != nil {
		return nil, fmt.Errorf("query GetSubscriptions: %w", err)
	}
	defer rows.Close()
	items := []GetSubscriptionsRow{}
	for rows.Next() {
		var item GetSubscriptionsRow
		if err := rows.Scan(&item.Token, &item.Posts, &item.Reposts, &item.Replies); err != nil {
			return nil, fmt.Errorf("scan GetSubscriptions row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close GetSubscriptions rows: %w", err)
	}
	return items, err
}

const clearTokenSQL = `UPDATE account SET token = NULL where id = $1;`

// ClearToken implements Querier.ClearToken.
func (q *DBQuerier) ClearToken(ctx context.Context, id string) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "ClearToken")
	cmdTag, err := q.conn.Exec(ctx, clearTokenSQL, id)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query ClearToken: %w", err)
	}
	return cmdTag, err
}

// textPreferrer wraps a pgtype.ValueTranscoder and sets the preferred encoding
// format to text instead binary (the default). pggen uses the text format
// when the OID is unknownOID because the binary format requires the OID.
// Typically occurs for unregistered types.
type textPreferrer struct {
	pgtype.ValueTranscoder
	typeName string
}

// PreferredParamFormat implements pgtype.ParamFormatPreferrer.
func (t textPreferrer) PreferredParamFormat() int16 { return pgtype.TextFormatCode }

func (t textPreferrer) NewTypeValue() pgtype.Value {
	return textPreferrer{ValueTranscoder: pgtype.NewValue(t.ValueTranscoder).(pgtype.ValueTranscoder), typeName: t.typeName}
}

func (t textPreferrer) TypeName() string {
	return t.typeName
}

// unknownOID means we don't know the OID for a type. This is okay for decoding
// because pgx call DecodeText or DecodeBinary without requiring the OID. For
// encoding parameters, pggen uses textPreferrer if the OID is unknown.
const unknownOID = 0
